### ISSUE TITLE
throws 404 error while creating repository

### ISSUE THREAD

**Issue by aamir-locus** [pulumi/pulumi-github#115]
Sample code:-
`example = github.Repository("example",
    description="My awesome codebase",
    template=github.RepositoryTemplateArgs(
        owner="mytest-org",
        repository="sample-pulumi-repo",
    ),
    visibility="public")`

Error response:-
Diagnostics:
  pulumi:pulumi:Stack (github-pulumi-dev):
    error: update failed
 
  github:index:Repository (example):
    error: POST https://api.github.com/repos/mytest-org/sample-pulumi-repo/generate: 404 Not Found []

▶ pulumi version
v2.23.2

**Comment by stack72** [comment]
Hi @aamir-locus 

It may sound like a basic question but does the GitHub Personal Access Token you are using have access to create repositories?

Paul

**Comment by aamir-locus** [comment]
Yes, It seems like the problem with the `template` block. I can create the repository on my account but not with the organisation account.

`example = github.Repository("example",
    description="My awesome codebase",
    visibility="public")`

`View Live: https://app.pulumi.com/aamir-locus/github-pulumi/dev/updates/38

     Type                        Name               Status      
     pulumi:pulumi:Stack         github-pulumi-dev              
 +   └─ github:index:Repository  example            created     
 
Resources:
    + 1 created
    1 unchanged

Duration: 9s`

**Comment by aamir-locus** [comment]
@stack72 Thank you so much for pointing me to the right direction. Adding GITHUB_ORGANIZATION solves the issue, however if I add `template=github.RepositoryTemplateArgs(owner="locus-taxy-devo",repository="my-test")` line it failed.

but this block works successfully  `example = github.Repository("example",
    #template=github.RepositoryTemplateArgs(owner="locus-taxy-devo",repository="my-test"),
    description="My awesome codebase",
    visibility="public")`. And repository created in my organisation. Thanks :)

**Comment by stack72** [comment]
happy it worked for you!
