### ISSUE TITLE
Admin access require for creating a repo in organisation.

### ISSUE THREAD

**Issue by aamir-locus** [pulumi/pulumi-github#116]
We are having Github organisation with enterprise account. And also set `GITHUB_TOKEN` and `GITHUB_ORGANIZATION` as environment variable. So when I tired to create repo with below code I got 403 error. But I can create repository with my user from UI.

Here's the error code.

` github:index:Repository (GithubRepo):
    error: POST https://api.github.com/orgs/locus-taxy/repos: 403 You need admin access to the organization before adding a repository to it. []`

**Comment by EvanBoyle** [comment]
@jaxxstorm any ideas?

**Comment by EvanBoyle** [comment]
@aamir-locus Have you tried using that token to create a repo with the github API or CLI? This should give you an indication on whether or not your token is appropriately scoped.

**Comment by aamir-locus** [comment]
@EvanBoyle This seems weird to me. I need admin access to create a repository. However I have a dev organisation where I have the admin access and I can create the repository there with pulumi provider as well as with the API

▶ curl -H "Authorization: token $TOKEN" --data '{"name":"aamir-pulumi-demo"}' https://api.github.com/orgs/$ORG/repos
{
  "message": "You need admin access to the organization before adding a repository to it.",
  "documentation_url": "https://docs.github.com/rest/reference/repos#create-an-organization-repository"
} 

So, my question here is, if the permission is the issue then I should not been able to create the repo with the Github UI with the same user.

**Comment by EvanBoyle** [comment]
@aamir-locus Unfortunately I don't have any additional information to offer on the consistency of the GitHub API and website experience. We don't maintain or have anything to do with their permission model. We just expose the API via the provider. 

It sounds like the behavior of the provider is consistent with the API, so I am going to close this issue out. Please feel free to open another issue if you discover bugs in the provider implementation.

**Comment by leezen** [comment]
@aamir-locus It might be worth taking a look at the token and ensuring it actually has the `public_repo` and `repo` scopes (see https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) or creating a new token with those scopes to make sure it works for you.
