### ISSUE TITLE
Environments support

### ISSUE THREAD

**Issue by hognevevle** [pulumi/pulumi-github#128]
Support for Github's new [Environments feature](https://docs.github.com/en/actions/reference/environments) would be great. A use case would be e.g. providing separate Github secrets per environment.

**Comment by mikhailshilkov** [comment]
Thank you @hognevevle for opening this issue!

I think this feature is requested upstream in https://github.com/integrations/terraform-provider-github/issues/528 Whenever it's available there, we'll ship it in the Pulumi provider.

If you agree, let's close this issue and track upstream.

**Comment by hognevevle** [comment]
@mikhailshilkov Great, I'm fine with that :)
