### ISSUE TITLE
Feature request: Autolink references

### ISSUE THREAD

**Issue by dududko** [pulumi/pulumi-github#143]
Support github Autolink references in pulumi. 

At the moment the GitHub API does not support Autolink references. https://github.community/t5/GitHub-API-Development-and/Support-autolink-reference-configuration-in-the-API/td-p/44850

**Comment by lukehoban** [comment]
This is tracked upstream in https://github.com/integrations/terraform-provider-github/issues/285.  Once that support is added, it will be pulled in here.

**Comment by renannprado** [comment]
@lukehoban the support has been added on the upstream :smile: :tada:
