### ISSUE TITLE
[Go] [Branch Protection] [Restrictions] unexpected result

### ISSUE THREAD

**Issue by dududko** [pulumi/pulumi-github#147]
While configuring the Restriction for a branch protection I have found multiple issues:

#### 1) It is not possible to just enable the Restrictions without specifying Users, Apps or Teams. At least one user, team or app must be specified. 
<img width="928" alt="Screen Shot 2021-08-04 at 1 32 23 PM" src="https://user-images.githubusercontent.com/1488511/128174432-a063f73b-f98e-45ba-8a6d-c6f66c4d4805.png">

I would like to just put this attribute to enable the Restrictions
```
			Restrictions: github.BranchProtectionV3RestrictionsArgs{},
```

#### 2) If I specify at least one user the Restrictions are enabled
```
			Restrictions: github.BranchProtectionV3RestrictionsArgs{
				Users: pulumi.StringArray{
					pulumi.String("dududko"),
				},
			},

```
![image](https://user-images.githubusercontent.com/1488511/128175050-40d8c2a0-9a6b-4152-9d33-da416878aff9.png)

#### 3) If I remove the user it is removed from github restrictions list, but the Restrictions itself is still enabled. There is no way to disable restrictions with pulumi after it is enabled.

**Comment by mjeffryes** [comment]
Unfortunately, it looks like this issue hasn't seen any updates in a while. If you're still encountering this problem, could you leave a quick comment to let us know so we can prioritize it?
