### ISSUE TITLE
Enable Auto-Merge Option

### ISSUE THREAD

**Issue by gsuess** [pulumi/pulumi-github#148]
GitHub has a relatively new option on repositories to enable an auto-merge feature. This feature is currently not supported by pulumi.

It would be great to add it, to support something like this:

```js
new github.Repository("test", { enableAutoMerge: true});
```

**Comment by stack72** [comment]
Marking this as waiting for https://github.com/integrations/terraform-provider-github/issues/649

**Comment by vubogovich** [comment]
https://github.com/integrations/terraform-provider-github/issues/649 is merged!

**Comment by stack72** [comment]
Thanks @vubogovich you are correct - this is already available in pulumi-github

**Comment by vubogovich** [comment]
Just noticed it was released in terraform provider 4.17.0 which got into pulumi-github 4.6.0 🎉
