### ISSUE TITLE
Renaming GitHub repository with Pulumi works but breaks the related repository resources

### ISSUE THREAD

**Issue by vubogovich** [pulumi/pulumi-github#161]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Renaming GitHub repository with Pulumi works but breaks `ActionsSecret` & `TeamRepository` resources.

### Steps to reproduce

1. Create a pulumi program which sets up a GitHub repository with a secret & team access.
2. `pulumi up`
3. Rename GitHub repository in the pulumi program and update `repository` prop for `ActionsSecret` & `TeamRepository` resources.
4. `pulumi up`

Expected: pulumi program is successfully executed and GitHub repository gets renamed.

Actual: GitHub repository gets renamed but pulumi program fails with
```
~  github:index:ActionsSecret {resource-name} updating [diff: ~repository]; error: Resource provider reported that the resource did not exist while updating {urn}
```
or pulumi fails to replace `TeamRepository` after repo is renamed as it tries to delete the one related to the previous repository name.

Do you have an example how to set up a GitHub repository with secrets and team access so it can be successfully renamed?

**Comment by mikhailshilkov** [comment]
The upstream issue was tracked in https://github.com/integrations/terraform-provider-github/issues/1753 and got resolved in https://github.com/integrations/terraform-provider-github/pull/1754.
