### ISSUE TITLE
pulumi import showing deprecated field name

### ISSUE THREAD

**Issue by tz-torchai** [pulumi/pulumi-github#208]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

### Steps to reproduce

pulumi cli: `v3.28.0` 

1. create a python project with `pulumi==3.29.0a1649432411`, `pulumi-githuib==4.11.0`
2. import a existing github repo with 
```
pulumi import github:index/repository:Repository  repo-slug repo-slug 
```
 
Expected: No warnings or better message
Here, it would better off to import the github repo with field `github_default_branch` instead of `default_branch`

Actual:  
```
    warning: urn:pulumi:prod::compute-infra::github:index/repository:Repository::compute-infra verification warning: "default_branch": [DEPRECATED] Use the github_branch_default resource instead
    warning: One or more imported inputs failed to validate. This is almost certainly a bug in the `github` provider. The import will still proceed, but you will need to edit the generated code after copying it into your program.
    warning: github:index/repository:Repository resource 'compute-infra' has a problem: "private": conflicts with visibility
```

For the first and the second warning, i suppose pulumi github provider should be updated to use the latest field name?

**Comment by tz-torchai** [comment]
OK, I figured this out the thrid warning: 
```
warning: github:index/repository:Repository resource 'compute-infra' has a problem: "private": conflicts with visibility
```
This is because `private` field is depracated and it has both two fields: `private` and `visibility` 

The warning message is not very intuitive.

**Comment by guineveresaenger** [comment]
Hi @tz-torchai - thank you for filing this issue!

It took me a while to dig through these but it looks like there's three separate things going on:

1. The first warning is an [upstream provider](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository#default_branch) issue - the field is deprecated but still exists, likely for backwards compatibility, and the import will attempt to duplicate, but warn you. This is  unfortunate, so we:

2. provide you with a warning on `pulumi import` that lets you know the generated code likely won't work as-is.

3. For the third warning, again we are surfacing a [deprecation](https://www.pulumi.com/registry/packages/github/api-docs/repository/#private_nodejs) that's still getting picked up by `import`.

While we wait for upstream to fully deprecate these fields, please refer to the [Pulumi GitHub package docs](https://www.pulumi.com/registry/packages/github/) to find the correct code to use.
