### ISSUE TITLE
ActionsOrganizationSecret should be treated as immutable

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi-github#257]
Due to bugs in the upstream terraform provider, `ActionsOrganizationSecret` behaves poorly during updates. All its fields should be marked immutable to allow the resource to be recreated.

_Originally posted by @viveklak in https://github.com/pulumi/pulumi-github/issues/249#issuecomment-1281700476_

**Comment by mikhailshilkov** [comment]
I don't think we want to override immutability in our provider. Instead, we'll track upstream changes on related fixes.
