### ISSUE TITLE
Export to cloud-native IaC

### ISSUE THREAD

**Issue by ubikusss** [pulumi/pulumi-github#267]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

One of the ways we use IaC in our company is to offer our customers an easy way to deploy our solutions. 
We also need to publish them in each cloud provider's marketplace. To do that we need to use cloud specific IaC option (AWS - CloudFormation, Azure - ARM templates, etc..).

Is there a way to export from Pulumi to cloud-native IaC?

**Comment by thomas11** [comment]
Hi @ubikusss, that's a great question. There is no ready-made export solution currently. Given the Pulumi model, this would be hard, and maybe impossible in all cases, to write. 

For the marketplace scenario, it may be possible to use an inverted approach: submit a small ARM/CloudFormation program which internally then runs Pulumi.

I'll close this issue but please feel free to respond anytime.
