### ISSUE TITLE
Is it possible to fork an existing repo in an organisation?

### ISSUE THREAD

**Issue by commandodev** [pulumi/pulumi-github#268]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I'd love to be able to fork an existing repo with this library. I have a load of infrastructure parameterised by some name.

I'd like to be able to fork `org/repo-template` to `org/{name}-repo`

So far I haven't been able to figure out what kind of access token I'd need for that or if there's anywhere in the API that allows forks.

**Comment by thomas11** [comment]
Hi @commandodev! Unfortunately, forking is not possible at the moment. This is due to [a limitation in the underlying Terraform provider](https://github.com/integrations/terraform-provider-github/issues/152). Sorry!

**Comment by commandodev** [comment]
Gotcha, thanks. As it turns out I can just fork the repo myself and then do everything else I need, so all good :-)
