### ISSUE TITLE
Creation of Custom Role resource not supported?

### ISSUE THREAD

**Issue by jetersen** [pulumi/pulumi-github#293]
## Hello!
https://github.com/integrations/terraform-provider-github/releases/tag/v5.10.0 mentions support for custom roles but I cannot see it in the documentation.

https://www.pulumi.com/registry/packages/github/api-docs/ 

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Custom roles is a GitHuB teams feature

### Affected area/feature

N/A

**Comment by iwahbe** [comment]
Hi @jetersen. We document support for custom roles on the resource they apply to: [github.RepositoryCollaborator](https://www.pulumi.com/registry/packages/github/api-docs/repositorycollaborator/). We mention them here for the permission input: 
<img width="764" alt="Screenshot 2023-01-19 at 2 24 56 PM" src="https://user-images.githubusercontent.com/22222529/213575944-81a8255e-f938-4eea-b682-c780d3925922.png">

Note: all our documentation is taken from the upstream provider.

**Comment by jetersen** [comment]
Ah bad naming I was expecting the name of `CustomRole` 😓

**Comment by jetersen** [comment]
@iwahbe would mind reopening? 😊

**Comment by iwahbe** [comment]
Sure. It sounds like the issue wasn't about missing documentation, but support for a resource that creates custom roles. Does that sound right?

Dispite https://github.com/integrations/terraform-provider-github/releases/tag/v5.10.0, I don't think that the upstream provider has support for creating custom roles. The tracking issue for adding that feature is https://github.com/integrations/terraform-provider-github/issues/1069.

**Comment by Jamess-Lucass** [comment]
I believe this can be marked as resolved now, the linked issue https://github.com/integrations/terraform-provider-github/issues/1069 has been merged in and `OrganizationCustomRole` has been added to the pulumi sdk.

**Comment by ericrudder** [comment]
thanks @Jamess-Lucass [btw, you don't look 23!  :)]
