### ISSUE TITLE
Missing documentation for ProviderAppAuth input

### ISSUE THREAD

**Issue by Hanskun** [pulumi/pulumi-github#348]
File: [themes/default/content/registry/packages/github/api-docs/provider/_index.md](https://www.pulumi.com/registry/packages/github/api-docs/provider/)

I have a attempted to use the GitHub provider along wiht a GitHub App I have created, but there is no documentation to the input fields to configure this. For the pemFile argument I am trying to provide a path to the pemFile, but it is giving me the error `error: no decodeable PEM data found`

So I think that I need to provide the PEM data directly in the input field, but there is no information regarding whether this should be base64 encoded or just as a plaintext string. Would appreciate if there was some additional documentation here to avoid the trial and error approach to have this work.

**Comment by guineveresaenger** [comment]
Hi @Hanskun - thank you for filing this issue! This is an instance of https://github.com/pulumi/pulumi-terraform-bridge/issues/1046 - we'll take a look as soon as we can.

**Comment by mnlumi** [comment]
The documentation is still an issue. The current docs show blank spaces here: <img width="747" alt="Screenshot 2023-07-20 at 11 29 36 PM" src="https://github.com/pulumi/pulumi-github/assets/118926824/4f99bb9b-a148-4dc4-b516-a0c4432a8b1c">

**Comment by nikaro** [comment]
Is there a way to pass the `app_auth` credentials into config without overriding the default provider?

I tried this without success:
```
config:
  github:app_auth:
    id:
      secure: ****
    installation_id:
      secure: ****
    pem_file:
      secure: ****
```

**Comment by guineveresaenger** [comment]
This should be fixed via https://github.com/pulumi/pulumi-terraform-bridge/pull/1650, and you should be seeing docs updates on the next release of this provider.
