### ISSUE TITLE
Bug: some kind of hash is appended to repository name after creation

### ISSUE THREAD

**Issue by arunsathiya** [pulumi/pulumi-github#548]
### What happened?

I am creating a repository on GitHub with the `github.Repository` resource, but the repository name specified in the configuration gets appended with a hash. 

### Example

My code is:

```go
package main

import (
	"github.com/pulumi/pulumi-github/sdk/v5/go/github"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		_, err := github.NewRepository(ctx, "repo", &github.RepositoryArgs{
			Description: pulumi.String("GitHub repo managed by Pulumi"),
			Visibility:  pulumi.String("public"),
		})
		if err != nil {
			return err
		}
		return nil
	})
}
```

In this case, the expected repository name is `repo` but what ends up being created is `repo-d1846bf`. The hash is random each time I run the command.

I cannot see anything wrong in the creation flow:

<img width="1335" alt="Screenshot 2024-01-24 at 10 48 03 PM" src="https://github.com/pulumi/pulumi-github/assets/18581859/486516b8-ae57-4dfe-9b80-81777eae0e6d">

### Output of `pulumi about`

```sh
CLI
Version      3.102.0
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME    VERSION
github  5.26.0
go      unknown

Host
OS       darwin
Version  14.3
Arch     arm64

This project is written in go: executable='/usr/local/go/bin/go' version='go version go1.21.5 darwin/arm64'

Backend
Name           pulumi.com
URL            https://app.pulumi.com/arunsathiya
User           arunsathiya
Organizations  arunsathiya
Token type     personal

Dependencies:
NAME                                    VERSION
github.com/pulumi/pulumi-github/sdk/v5  5.26.0
github.com/pulumi/pulumi/sdk/v3         3.102.0

Pulumi locates its logs in /var/folders/hg/fpn4hksd7qb70r11v5rywzs40000gn/T/ by default
warning: Failed to get information about the current stack: No current stack
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by marco-m** [comment]
Hello, this is due to the difference between logical and physical names.
The default Pulumi behavior makes a lot of sense, but not to create GitHub repos :-)
See https://www.pulumi.com/docs/concepts/resources/names/ for how to override and the caveats that go with it.

**Comment by arunsathiya** [comment]
Thank you, @marco-m! That page helps, and clearly an user error, not a bug in the provider. Closing this issue.
