### ISSUE TITLE
RepositoryEnvironment does not support prevent_self_review

### ISSUE THREAD

**Issue by jku** [pulumi/pulumi-github#557]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

GitHub deployment environments support the boolean argument `prevent_self_review`, see [GitHub docs on environments](https://docs.github.com/en/rest/deployments/environments?apiVersion=2022-11-28#create-or-update-an-environment)

Pulumi does not expose this argument: https://www.pulumi.com/registry/packages/github/api-docs/repositoryenvironment/

### Affected area/feature

This is very likely a minor change in the github provider only.

**Comment by t0yv0** [comment]
Thank you for reporting this @jku 

Pulumi provider is tracking the upstream provider for this feature.

prevent_self_review is available in 6.x.x RC:

https://github.com/integrations/terraform-provider-github/blob/v6.0.0-rc1/github/resource_github_repository_environment.go#L42

But it is not available in 5.45.0 version this provider is currently tracking. It will become available once upstream releases 6.x and pulumi-github catches up. Thank you for your patience.

**Comment by jku** [comment]
fixed now,thanks
