### ISSUE TITLE
Repository(description=None) unexpected behaviour

### ISSUE THREAD

**Issue by felix11h** [pulumi/pulumi-github#56]
I have only been working with Pulumi for a couple of weeks, so please excuse if I am making any faulty assumptions. For Pulumi managed GitHub organizations, in my understanding, when creating a repository with configuration option with parameter value `None`, these options are not set. For example

```python
github.Repository(..., private=None, ...) 
```

does not modify an existing repository's private/public visibility.  Similarly, other repository settings can remain untouched by Pulumi, while a select few are adjusted.

This is however not the case for `description`. An existing description of a repository gets removed when `None` is set,

```python
github.Repository(..., description=None, ...) 
```
yields

```
[provider=...]
      - description : "some previously existing description"
```
meaning the the existing description gets removed.

I would like to be able to keep existing descriptions in place without having to explicitly set them in Pulumi. This would for example be very helpful for managing repositories that were forked from another repository. Is there an alternative to `description=None` or could it be considered to make that operate more in line with other parameters being set to `None`?

**Comment by felix11h** [comment]
It seems that I was wrong, also other parameters with `None` have default values. I forgot to call a `pulumi refresh` when testing this. I would still be interested to know if there is a way to keep existing values intact without overriding them by defaults. This issue here should be closed, however.

**Comment by lukehoban** [comment]
> keep existing values intact

What precisely do you mean by this?  Do you have resources created outside Pulumi that you are modifying using Pulumi?  Or are the resources created and managed with Pulumi but then modified outside Pulumi?

In general Pulumi is a desired state configuration model, so it specificity the desired state of any resources that it manages. If you have changes you expect to make from that desired state outside of Pulumi, you can use ignoreChanges (https://www.pulumi.com/docs/intro/concepts/programming-model/#ignorechanges).

**Comment by felix11h** [comment]
> Do you have resources created outside Pulumi that you are modifying using Pulumi? Or are the resources created and managed with Pulumi but then modified outside Pulumi?

The first case, resources created outside Pulumi. We have an existing GitHub organization that we would like to manage with Pulumi going forward. I wasn't aware of the `ignoreChanges` option, it seems that it solves my problem perfectly. If a specific resource option wasn't specified in our config (has value `None`), I can tell Pulumi to ignore changes for this resource option and the current state, for example an existing description of a GitHub repository, will be preserved.

Thank you very much for the helpful reply!
