### ISSUE TITLE
`BranchProtection.get` appears to be broken

### ISSUE THREAD

**Issue by talhashraf** [pulumi/pulumi-github#605]
### What happened?

`BranchProtectionV3.get` expects `id` to be in a format of `{repository_name}:{branch_name}`. However, `BranchProtection.get` expects `id` to be a resource-provider ID, which is a random string of characters. There is no way to fetch that random resource ID. Additionally, the [GitHub API](https://docs.github.com/en/rest/branches/branch-protection?apiVersion=2022-11-28) does not require such an ID.

* [BranchProtectionV3](https://www.pulumi.com/registry/packages/github/api-docs/branchprotectionv3/)
* [BranchProtection](https://www.pulumi.com/registry/packages/github/api-docs/branchprotection/#branchprotectionrequiredstatuscheck)

### Example

Example of `BranchProtectionV3.get`, which works fine:

```
BranchProtectionV3.get(
    f"{stack}-{repository_name}-{branch_name}-get-branch-protection",
    f"{repository_name}:{branch_name}",
    branch=branch_name,
    repository=repository.name,
)
```

Example of `BranchProtection.get`, where problem is:

```
BranchProtection.get(
    f"{stack}-{repository_name}-{branch_name}-get-branch-protection",
    "DZX_2rahdgx7gnxvpz", # Problem: From where do we fetch this ID? Does that belong to Pulumi or GitHub API?
    pattern=branch_name,
    repository_id=repository.name,
)
```

Error log.

```
Previewing update (talha):
     Type                              Name                                                       Plan     Info
     pulumi:pulumi:Stack               default-config-talha                                               1 error
     └─ github:index:BranchProtection  talha-brown-repuve-puppeteer-trunk-get-branch-protection           1 error


Diagnostics:
  pulumi:pulumi:Stack (default-config-talha):
    error: preview failed

  github:index:BranchProtection (talha-brown-repuve-puppeteer-trunk-get-branch-protection):
    error: Preview failed: resource 'brown-repuve-puppeteer:trunk' does not exist
```

### Output of `pulumi about`

```
CLI          
Version      3.76.1
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME           VERSION
aws            5.42.0
command        0.8.1
docker         4.3.2
gcp            6.62.0
github         6.1.0
google-native  0.31.1
kubernetes     4.1.0
python         unknown
random         4.13.2
sentry         0.0.8

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in python: executable='/home/talha/.cache/pypoetry/virtualenvs/cloud-infra-nbCDz0hn-py3.11/bin/python3' version='3.11.3
'

Backend        
Name           vmware
URL            gs://talha-gcp-infra/pulumi-state/
User           talha
Organizations  

Dependencies:
NAME                  VERSION
cloud-infra           0.1.0
cryptography          42.0.5
grpcio-status         1.56.0
pip                   24.0.0
pulumi_aws            5.42.0
pulumi_command        0.8.1
pulumi_docker         4.3.2
pulumi_gcp            6.62.0
pulumi_github         6.1.0
pulumi_google_native  0.31.1
pulumi-kubernetes     4.1.0
pulumi_random         4.13.2
pulumiverse_sentry    0.0.8
PyGithub              2.2.0
pytest                7.4.0
setuptools            69.1.0
wheel                 0.42.0

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the current stack: No current stack
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @talhashraf - thank you for filing this issue.

It would help us a lot in debugging this if you could provide us with a complete program that reproduces this behavior. 🙏

**Comment by talhashraf** [comment]
I am unavailable for a couple of weeks. I will provide more details when I join back.

For a quick note, removing `pattern` and `repository_id` parameters solves the error.

**Comment by mikhailshilkov** [comment]
Marking for re-triage again, I feel like the provided snippets are enough for that

**Comment by guineveresaenger** [comment]
Hi @talhashraf - I'm glad you found a workaround.

I made an attempt at a repro, although I do not know your particular setup.

With a correctly scoped org token and `GITHUB_OWNER` set to `pulumi`, the following worked for me (substitute a different org/repo that's scoped to your accesses):

```
import pulumi
import pulumi_github as github

github.BranchProtection.get(
    "get-branch-protection",
    "pulumi-aiven:master"
)
```

To answer your question regarding the `id` field - it looks like for `BranchProtection` the format is `repo:branch`. [It doesn't look like `pattern` or `repository_id` are supported.](https://www.pulumi.com/registry/packages/github/api-docs/branchprotection/#look-up)

Please feel free to reopen this issue if there are any remaining questions.

**Comment by EronWright** [comment]
To clarify, the `DZX_2rahdgx7gnxvpz` value in the example of `BranchProtection.get` refers to the `id` field of the `BranchProtectionRule` object in the GitHub GraphQL API ([reference](https://docs.github.com/en/graphql/reference/objects#branchprotectionrule)), and is generated by GitHub. [Here's](https://gist.github.com/duboisf/d48695e36327959c11efe8543508da0e) a snippet showing how to query the GitHub GraphQL API.
