### ISSUE TITLE
Environment Deployment Policy for tags

### ISSUE THREAD

**Issue by av-andrii-ievtukhov** [pulumi/pulumi-github#692]
Hey guys! 

We have a repository where we have to support deployments from both branches and tags, and we are not able to find information regarding tags in pulumi documentation here - https://www.pulumi.com/registry/packages/github/api-docs/repositoryenvironmentdeploymentpolicy/.

It seems it only supports the `branchPattern` option, not the `tagPattern` option.

--- 

What we want to achieve: 

![image](https://github.com/pulumi/pulumi-github/assets/116803006/27b06ab7-54ee-4e42-9666-9f93bf07e197)

---

If there is a way to do it now, or maybe add this feature -> would be great)

Thanks!

**Comment by mjeffryes** [comment]
Hi @av-andrii-ievtukhov this is a great suggestion, but the reason we don't have the `tagPattern` on this resource today is that the upstream terraform provider only has `branchPattern` (see [github_repository_environment_deployment_policy | Terraform Registry](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository_environment_deployment_policy)).

If you file an issue against https://github.com/integrations/terraform-provider-github and get the support added there, we'll pick it up in our provider soon after it's released there.

**Comment by maksym-lutskyi** [comment]
Hi
They actually have already opened issue for that. But unfortunately PR for that is still in open state.
https://github.com/integrations/terraform-provider-github/pull/2165
