### ISSUE TITLE
Pulumi confused about existence of Github Actions Variables

### ISSUE THREAD

**Issue by james-tindal** [pulumi/pulumi-github#731]
### Describe what happened

Pulumi gets stuck unable to delete an already deleted variable. This blocks other resources from updating.

## How to reproduce
* Download the example repo at [james-tindal/pulumi-github-variable-bug](https://github.com/james-tindal/pulumi-github-variable-bug).
* Ensure github:token and config:repository are configured.
* `pulumi up`
* `pulumi down`
  * Select "yes" to perform the destroy
  * Quickly press`ctrl-c` to stop it before it announces it is working

This results in a stack that can never be destroyed or have the Github variable removed from it.

### Sample program

Sample repo at [james-tindal/pulumi-github-variable-bug](https://github.com/james-tindal/pulumi-github-variable-bug).

```ts
import * as pulumi from '@pulumi/pulumi'
import * as github from '@pulumi/github'

const repository = new pulumi.Config('config').require('repository')

new github.ActionsVariable('github-variable', {
  repository,
  variableName: 'test',
  value: 'test',
})
```

### Log output

<img width="1083" alt="image" src="https://github.com/user-attachments/assets/09e3209b-861a-47c7-b27a-1223ddcc5cfc">

### Output of `pulumi about`

<details>

```
CLI
Version      3.124.0
Go Version   go1.22.5
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  github  6.2.3
language  nodejs  unknown

Host
OS       darwin
Version  14.5
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v22.4.1'

Backend
Name           pulumi.com
URL            https://app.pulumi.com/uJEmLiaoJzSIsPRHtHQynpXoYqP5b4sMeLmhJywZ
User           uJEmLiaoJzSIsPRHtHQynpXoYqP5b4sMeLmhJywZ
Organizations  uJEmLiaoJzSIsPRHtHQynpXoYqP5b4sMeLmhJywZ
Token type     personal

Pulumi locates its logs in /var/folders/_8/k71zvsq96fz4rvtrdyygkhx00000gp/T/ by default
warning: Failed to get information about the Pulumi program's dependencies: could not find either /Users/user/code/pulumi-github-variable-bug/yarn.lock or /Users/user/code/pulumi-github-variable-bug/package-lock.json
warning: Failed to get information about the current stack: No current stack
```
</details>

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @james-tindal. I'm sorry that you hit this. When you cancel a Pulumi operation, some providers are left unaware of the state.

I'm assuming what happens is that the provider deletes the action variable, but then is canceled before it can inform Pulumi that the variable has been deleted. This means that your Pulumi stack's state is out of sync with GitHub. To fix this, please run `pulumi refresh`. You should then be able to run `pulumi down`.

**Comment by james-tindal** [comment]
Great. Thanks!
