### ISSUE TITLE
Upgrade to GitHub Terraform Provider versions beyond v4.1.0

### ISSUE THREAD

**Issue by felix11h** [pulumi/pulumi-github#90]
The current version of the GitHub Terraform provider is 4.3.0 and it would be great if the Pulumi GitHub module could be upgraded to that version (currently on v4.1.0).

Possibly the new version releases have not been noticed as the GitHub Terraform provider has recently [migrated](https://github.com/integrations/terraform-provider-github/issues/656) to a [new repository](https://github.com/integrations/terraform-provider-github). 

Thank you!

**Comment by stack72** [comment]
Thanks so much for this repo @felix11h - this slipped past me that they migrated - upgrade PR on the way

Paul
